---
- name: Converge
  hosts: all
  vars:
    rpmbuild_options: "-bb --with baseonly --without debuginfo"
  roles:
    - role: ansible_role_fedora_kernel_lts
  post_tasks:
    - name: Find the kernel RPMs
      find:
        path: /home/vagrant/rpmbuild/RPMS/x86_64/
        patterns: '*.rpm'
        excludes: '*.src.rpm,*.srpm'
      register: find_kernel_rpms

    - name: Installing the kernel RPMs
      dnf:
        name: "{{ find_kernel_rpms.files | map(attribute='path') | list }}"
        state: present
      become: true

    - name: Reboot the virtual machine
      shell: sleep 5s; shutdown -r now
      # An async longer than a few seconds is required
      # so that Ansible does not notice that the SSH
      # connection was lost.
      async: 5
      poll: 0
      become: true

    - name: Wait for the virtual machine to finish rebooting
      wait_for_connection:
        delay: 10
        sleep: 5
        connection_timeout: 60

    - name: Find the kernel version is running
      command: uname -r
      register: kernel_version_current

    - name: Verify that the new kernel is running
      fail:
        msg: The new kernel was not installed correctly
      when: kernel_version_current.stdout != "4.14.59-300.lts.fc28.x86_64"

    - debug:
        msg: "Converge success!"
